version: '3'

services:
  bop-consus-importing-rdf:
    image: bop/bop-importing-rdf
    logging:
      options:
        max-size: "50m"
    environment:
      - JAVA_OPTS=-Xms200m -Xmx1g
    volumes:
      - ./data:/usr/verticles/data/
  piveau-consus-exporting-hub:
    image: registry.gitlab.com/piveau/consus/piveau-consus-exporting-hub
    logging:
      options:
        max-size: "50m"
    environment:
      - JAVA_OPTS=-Xms200m -Xmx2g
      - PIVEAU_HUB_APIKEY=yourRepoApiKey
      
  piveau-consus-scheduling:
    image: registry.gitlab.com/piveau/consus/piveau-consus-scheduling
    logging:
      options:
        max-size: "50m"
    ports:
      - '8090:8080'
      - '8095:8085'
      - '5001:5000'
    environment:
      - JAVA_OPTS=-Xms100m -Xmx200m
      - PIVEAU_SHELL_CONFIG={"telnet":{},"http":{}}
    volumes:
      - ./pipes:/usr/verticles/pipes
