version: '3'

services:
  piveau-consus-importing-rdf:
    build: piveau/piveau-consus-importing-rdf
    logging:
      options:
        max-size: "50m"
    environment:
      - JAVA_OPTS=-Xms200m -Xmx500m
  piveau-consus-exporting-hub:
    build: piveau/piveau-consus-exporting-hub
    logging:
      options:
        max-size: "50m"
    environment:
      - JAVA_OPTS=-Xms200m -Xmx1g
      - PIVEAU_HUB_APIKEY=yourRepoApiKey

  piveau-consus-scheduling:
    build: piveau/piveau-consus-scheduling
    logging:
      options:
        max-size: "50m"
    ports:
      - '8090:8080'
      - '8095:8085'
      - '5000:5000'
    environment:
      - JAVA_OPTS=-Xms100m -Xmx200m
      - PIVEAU_SHELL_CONFIG={"telnet":{},"http":{}}
    volumes:
      - ./pipes:/usr/verticles/pipes
